### ISSUE TITLE
 ModuleNotFoundError: No module named 'user'

### ISSUE THREAD

**Issue by WilliamH07** [DanielShemesh/gpt4free-colab#1]
Hi there,

I'm having trouble with Google Colab. When I try to execute the prompt, it doesn't work and I receive the following error message:

`ModuleNotFoundError: No module named 'user' `

I have run every steps before, but nothing
Thanks

**Comment by WilliamH07** [comment]
The error changed when I switch to an another model now its : `KeyError: 'gpt-3.5-turbo'` or `KeyError: 'gpt-4'` ...

**Comment by WilliamH07** [comment]
I successfully installed the gpt4free repository on my local machine, so i dont need help anymore. Thanks a lot

**Comment by snowbrood** [comment]
I am having similiar problem. >>` ModuleNotFoundError: No module named 'user' `

I woder how you solved it

**Comment by WilliamH07** [comment]
I didnt use this colab projet, but the original from : https://github.com/xtekky/gpt4free. 
You may have some issue because it need some change to make it work. If you try using it and it dont works, tell me and Im going to tell you the steps I did to make it work
